### ISSUE TITLE
Pinny blocks tapping for tap targets when open. Requires multiple taps.

### ISSUE THREAD

**Issue by scalvert** [mobify/pinny#28]
When opening pinny that contains a bellows, the bellows headers require multiple taps to open. In some cases, once open they cannot be closed.

**Comment by fractaltheory** [comment]
Ted was mentioning that it was probably bouncefix related, and when bouncefix is disabled the issue no longer occurs.

**Comment by Helen-Mobify** [comment]
@fractaltheory @kpeatt 

It is indeed because of fastclick and bouncefix.

Bouncefix shifts the scroll-able container by 1 px. During the shift, it cancels out the click initiated by fastclick. Normally, the mobile browser only triggers the click after 300ms. Which is why when Bouncefix or Fastclick is used independently, you don't see the issue.

**Comment by scalvert** [comment]
Let's just fork bouncefix and apply the fix there!
